service:
  name: payment

plugins:
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-domain-manager

custom:
  prune:
    automatic: true
    number: 2
  serverless-iam-roles-per-function:
    defaultInherit: true
  domainNameMap:
    default: api.development.nevvi.net
    production: api.nevvi.net
  basePathMap:
    production: payment
    development: payment
    default: ${self:provider.stage}-payment
  customDomain:
    domainName: ${self:custom.domainNameMap.${self:provider.stage}, self:custom.domainNameMap.default}
    basePath: ${self:custom.basePathMap.${self:provider.stage}, self:custom.basePathMap.default}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: payment-${self:provider.stage}
  stackName: payment-${self:provider.stage}
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}

functions:
  paymentAuthorizer:
    handler: src/functions/Authorizer.authorize
  createToken:
    handler: src/functions/PaymentHandler.createToken
    events:
      - http:
          path: /v1/token
          method: post
          authorizer:
            name: paymentAuthorizer
            resultTtlInSeconds: 0
            type: request
  createTransaction:
    handler: src/functions/PaymentHandler.createTransaction
    events:
      - http:
          path: /v1/transaction
          method: post
          authorizer:
            name: paymentAuthorizer
            resultTtlInSeconds: 0
            type: request